# Generated by Django 3.1.7 on 2021-06-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
